#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require './helpers.rb'
require './conversion.rb'
require './category.rb'
require './hashtag.rb'
require './page.rb'
require './page_count.rb'
require './redirection.rb'

force = ARGV.include?("-f")
verbose = ARGV.include?("-v")
case ARGV.first
when "convert"
  Conversion.do(force)
when "fetch"
  dest_db = SQL.connect("dest")
  Page.fetch_content(dest_db, force)
when "category"
  Category.do(force)
when "hashtag"
  Hashtag.do
when "redirection"
  Redirection.do(force)
when "page_count"
  PageCount.do(force, verbose)
else
  puts "Unknown command."
end
